# Generated by Django 4.1.6 on 2023-02-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
